name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: badelhadocker.azurecr.io
        username: BadelhaDocker
        password: wEVH1Pk7gCsxwpxmw/8cxtlZQLr4lAvxMFsMJH2a5z+ACRBsuCtW

    - name: Build Docker Image
      run: |
        docker build -t badelhadocker.azurecr.io/hellodocker2:${{ github.sha }} .

    - name: Push Docker Image to Azure Container Registry
      run: |
        docker push badelhadocker.azurecr.io/hellodocker2:${{ github.sha }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.28.9'

    - name: Get AKS credentials
      run: |
        az login --service-principal -u 272105d5-0143-49f6-9695-793aef856e6d -p thW8Q~wLCnecgH1dAr1uSRTvCA_AKB-jLwkM0aPV --tenant bded4dcc-cc45-4b9a-bda4-b1430f6c7f6f
        az aks get-credentials --resource-group 202101031_rg_4516 --name myAKSCluster

    - name: Deploy to AKS
      run: |
        sed -i 's|image: badelhadocker.azurecr.io/hellodocker2:latest|image: badelhadocker.azurecr.io/hellodocker2:${{ github.sha }}|' deployment.yaml
        kubectl apply -f deployment.yaml
